# -*- coding: utf-8 -*-
"""Basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QRj_snJCi7uFX7L7bZwbikd8N4tH1YCQ
"""

print("hello world")

"""Artehmic Operator"""

4 + 2
5 / 3
8 * 1
4 % 2
3 ** 2

"""Variable and Data type"""

a = 4
print(type(a))
b = 9.1
print(type(b))
c = a + b
print(c)
s = 'hello world'
print(type(s))
print(s)

x = 3
y = 4
z = y ** x
y = 5
print(z)

"""Conditional Logic"""

#user input
# input() take input as string : so we need to type cast in int
marks = input("Enter your number !")
print(type(marks))
marks = int(marks)

#conditional operation
if marks >= 40:
  print("congratulations Your passed")
else :
  print("Hard luck! you failled !")

#user input

marks = int(input("Enter your Number : "))
if marks >= 80:
  print("Your GPA: A+")
elif marks >= 70:
  print("Your GPA: A")
elif marks >= 60:
  print("Your GPA: B")
elif marks >= 50:
  print("Your GPA: C")
else :
  print("You are failed in exam")

print("done XD")

#n is positive or negitive and odd or even

n = int(input("Enter the number: "))

if n >= 0 and n % 2 == 0 :
  print(n, "is positive and even number!")
elif n < 0 and n % 2 == 0:
  print(n, "is negative number and even number!")
elif n >= 0 and n % 2 == 1:
  print(n, "is positive and odd number")
else :
  print(n, "is negative number andd odd number")

"""Leap Year"""

year = int(input("Year : "))

if year % 100 == 0 and year % 400 == 0 :
  print(year, "is leap year!")
elif year % 4 == 0 and year % 100 != 0 :
  print(year, "is leap year!")
else :
  print(year, "is not a leap year!")

"""**List**

"""

my_fruits = ['apple', 'banana', 'mango', 'goava']
print(type(my_fruits))
print(my_fruits)

# access by index
print(my_fruits[0])

#insert a new value
my_fruits.append("papaia")
print(my_fruits)
print(len(my_fruits))

#cheeck is the value have in list
print('mango' in my_fruits)
print('orange' in my_fruits)

print(my_fruits)
my_fruits.pop()
print(my_fruits)
my_fruits.pop()
print(my_fruits)

"""Function"""

from re import M
def multipliction_table(n):
  print(n ,"x 1 = ",n * 1)
  print(n ,"x 2 = ",n * 2)
  print(n ,"x 3 = ",n * 3)
  print(n ,"x 4 = ",n * 4)
  print(n ,"x 5 = ",n * 5)
  print(n ,"x 6 = ",n * 6)
  print(n ,"x 7 = ",n * 7)
  print(n ,"x 8 = ",n * 8)
  print(n ,"x 9 = ",n * 9)
  print(n ,"x 10 = ",n * 10)

n = int(input("Your number : "))
multipliction_table(n)
multipliction_table(n + 1)
multipliction_table(n + 2)

"""**Bulid-in Function**

[W3School](https://www.w3schools.com/python/python_ref_functions.asp)   
[Python org](https://docs.python.org/3/library/functions.html)  
[Geeks for geeks](https://docs.python.org/3/library/functions.html)

Loop
"""

n = int(input("enter your number: "))

for i in range(1, n + 1, 1):
    print(i)
print("")
for i in range(n  , 0, -1):
    print(i)

def multipliction_table(n) :
  for i in range(1, 11):
    #print(n," X ", i ," = ", n * i)
    #using formating
    print("{} x {} = {}".format(n, i, n * i))

n = int(input("input your number : "))
for i in range(1, n + 1):
  multipliction_table(i)
  print(" ")

"""String

---


"""

s = 'abcdefg'
print(type(s))

#concatinate
print('10' + '10')
print('Bangladesh ' * 5)
print('4 ' * 10)

#len
print(len(s))

#acessing by index
print(s[1:5]) #print bcde
print(s[:]) #print full string
print(s[-1]) #print the last value of string
print(s[-2:]) #print last two value of stirng
print(s[0]) #print 0 index value
print(s[1]) # print first index value

#upper case and lower case
name = 'jahid'
name = name.upper()
print(name)
print(name.lower())
print(name.capitalize())

#find substirng
c = "Bangladesh"
print(c.find("Bangla")) #give output by index
print(c.find("desh"))